import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/server/auth";
import { Toaster } from "react-hot-toast";
import { cache } from "react";
import SidebarWrapper from "./_components/SidebarWrapper";

export const metadata: Metadata = {
  title: "Project Management App",
  description: "Generated by KK~Sharma",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const getSession = cache(() => auth());
  // cache is Reduces duplicate async calls to auth() when RootLayout re-renders. and Improves performance during SSR and RSC hydration.
  const session = await getSession();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <SessionProvider session={session}>
            <Toaster />
            <div className="flex h-screen bg-gray-50">
              <SidebarWrapper />
              <main className="flex-1 overflow-auto">{children}</main>
            </div>
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
